#!/usr/bin/env python
"""Compose a lens's carousel chip out of the lens's own art layers.

A thumbnail drawn by hand drifts: the art moves, the chip does not, and nothing catches it because
no test can see a drawable. This scales and translates the *shipped* path data into one square
viewport instead, so the chip is derived from the art rather than a second drawing of it.

Only the absolute `M`/`L`/`C`/`Z` subset this repo's vector art uses is understood — that is all
`swarm/tools/preview_lens.py` rasterises too, and a path this cannot transform is one that tool
cannot preview.

Square on purpose: `LensCarousel` fits each thumbnail inside a circle, so wide art (the Shades
strip, a hat brim) letterboxes to a sliver on its own and the corners have to stay clear for the
crop.

Usage
-----
    python swarm/tools/compose_lens_thumbnail.py \\
        --out app/src/main/res/drawable/lens_cowboy.xml --viewport 320 \\
        --layer lens_cowboy_hat.xml:300:10:34 \\
        --layer lens_cowboy_mustache.xml:224:48:190

Each `--layer` is `file:width:x:y` — the drawn width in the output viewport, and where its
top-left corner lands. Layers composite in the order given.
"""

from __future__ import annotations

import argparse
import re
import xml.etree.ElementTree as ET
from pathlib import Path

ANDROID = "{http://schemas.android.com/apk/res/android}"
DRAWABLES = Path("app/src/main/res/drawable")
# Same alphabet swarm/tools/preview_lens.py tokenises; the arc command is matched so it can be
# rejected by name below rather than silently swallowed as a number.
TOKEN = re.compile(r"[MCLAZmclaz]|-?\d*\.?\d+")
SUPPORTED = frozenset(("M", "L", "C", "Z"))


def transform(data: str, scale: float, dx: float, dy: float) -> str:
    """Scale and translate absolute path data, re-emitted one command per line."""
    commands: list[tuple[str, list[float]]] = []
    for token in TOKEN.findall(data):
        if token.isalpha():
            if token.upper() not in SUPPORTED:
                raise SystemExit(f"unsupported path command {token!r}")
            commands.append((token.upper(), []))
        elif commands:
            commands[-1][1].append(float(token))

    lines = []
    for command, numbers in commands:
        moved = [
            value * scale + (dx if index % 2 == 0 else dy)
            for index, value in enumerate(numbers)
        ]
        pairs = [f"{moved[i]:g},{moved[i + 1]:g}" for i in range(0, len(moved) - 1, 2)]
        lines.append(command + " ".join(pairs))
    return "\n            ".join(lines)


def paths_of(source: Path, scale: float, dx: float, dy: float):
    for node in ET.parse(source).getroot().findall("path"):
        yield node.get(ANDROID + "fillColor"), transform(
            node.get(ANDROID + "pathData"), scale, dx, dy
        )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--viewport", required=True, type=int, help="square viewport size")
    parser.add_argument(
        "--layer",
        required=True,
        action="append",
        metavar="FILE:WIDTH:X:Y",
        help="a drawable in app/src/main/res/drawable, its drawn width, and its top-left corner",
    )
    args = parser.parse_args()

    body = []
    for spec in args.layer:
        name, width, dx, dy = spec.rsplit(":", 3)
        source = DRAWABLES / name
        viewport_width = float(ET.parse(source).getroot().get(ANDROID + "viewportWidth"))
        body.append(f"\n    <!-- {source.stem} -->\n")
        for colour, data in paths_of(source, float(width) / viewport_width, float(dx), float(dy)):
            body.append(
                f'    <path\n        android:fillColor="{colour}"\n'
                f'        android:pathData="{data}" />\n'
            )

    header = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!--\n"
        "    GENERATED by swarm/tools/compose_lens_thumbnail.py — do not hand-edit. Every path\n"
        "    below is one of the lens's own art layers, scaled and translated into this square,\n"
        "    so the carousel chip cannot drift away from what the lens paints on a face. The exact\n"
        "    command that produced it is in the lens's KDoc in Lens.kt.\n"
        "-->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{args.viewport // 4}dp"\n'
        f'    android:height="{args.viewport // 4}dp"\n'
        f'    android:viewportWidth="{args.viewport}"\n'
        f'    android:viewportHeight="{args.viewport}">\n'
    )
    args.out.write_text(header + "".join(body) + "</vector>\n", encoding="utf-8")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
